# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/
env:
  - SWIFT_VERSION=5.3
  
os:
#  - linux
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode12
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
 
script:
  - swift build
#  - swift build -c release
