# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/
env:
  - SWIFT_VERSION=5.3
  
os:
#  - linux
  - osx
  
language: generic
sudo: required
dist: bionic

osx_image: xcode12

compiler:
    - clang
    - gcc
    
addons:
  apt:
    packages:
      - libz-dev
      
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
 
script:
  - mkdir build && pushd build
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)
  - popd && rm -rf build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e /usr/local/include/zstd_errors.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e /usr/local/include/zstd.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e /usr/local/lib/libzstd.a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e /usr/local/lib/libzstd.so; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e /usr/local/include/zstd_errors.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e /usr/local/include/zstd.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e /usr/local/lib/libzstd.a; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e /usr/local/lib/libzstd.dylib; fi
  - swift build
  - swift test --enable-test-discovery
#  - swift build -c release
